<a href="https://colab.research.google.com/github/coder-manisha/diabetes-prediction/blob/main/DL_poject2_tips.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns

###### to get dataset name ('tips') : search in google :load dataset in seaborn documentation  ---> click on first link-->again click on the name dataset link --> search for related dataset name --> then write that name here .

In [2]:
df = sns.load_dataset('tips')

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
dictionary1 = {'Female':0,'Male':1}
df['sex'] = df['sex'].map(dictionary1)
df.head()

   total_bill   tip sex smoker  day    time  size
0       16.99  1.01   0     No  Sun  Dinner     2
1       10.34  1.66   1     No  Sun  Dinner     3
2       21.01  3.50   1     No  Sun  Dinner     3
3       23.68  3.31   1     No  Sun  Dinner     2
4       24.59  3.61   0     No  Sun  Dinner     4

In [5]:
df['smoker'].unique()

['No', 'Yes']
Categories (2, object): ['Yes', 'No']

In [6]:
dictionary2 = {'No':0,'Yes':1}
df['smoker'] = df['smoker'].map(dictionary2)
df.head()

   total_bill   tip sex smoker  day    time  size
0       16.99  1.01   0      0  Sun  Dinner     2
1       10.34  1.66   1      0  Sun  Dinner     3
2       21.01  3.50   1      0  Sun  Dinner     3
3       23.68  3.31   1      0  Sun  Dinner     2
4       24.59  3.61   0      0  Sun  Dinner     4

In [7]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [8]:
dictionary3 = {'Sun':1,'Sat':2,'Thur':3,'Fri':4}
df['day']=df['day'].map(dictionary3)
df.head()

   total_bill   tip sex smoker day    time  size
0       16.99  1.01   0      0   1  Dinner     2
1       10.34  1.66   1      0   1  Dinner     3
2       21.01  3.50   1      0   1  Dinner     3
3       23.68  3.31   1      0   1  Dinner     2
4       24.59  3.61   0      0   1  Dinner     4

In [9]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [10]:
dictionary4 = {'Dinner':0,'Lunch':1}
df['time'] = df['time'].map(dictionary4)
df.head()

   total_bill   tip sex smoker day time  size
0       16.99  1.01   0      0   1    0     2
1       10.34  1.66   1      0   1    0     3
2       21.01  3.50   1      0   1    0     3
3       23.68  3.31   1      0   1    0     2
4       24.59  3.61   0      0   1    0     4

###### x axis contains all columns except tip and y is assigned to tip because we have to find tip

In [11]:
x = df.drop('tip',axis=1)
y = df['tip']

In [12]:
import tensorflow as tf
import numpy as np

In [13]:
#step1 : create neuron layers with neurons

layer1 = tf.keras.layers.Dense(units=4 , input_dim =6)
layer2 = tf.keras.layers.Dense(units=32)
layer3 = tf.keras.layers.Dense(units=32)
layer4 = tf.keras.layers.Dense(units=64)
layer5 = tf.keras.layers.Dense(units=64)
layer10 = tf.keras.layers.Dense(units=64)
layer6 = tf.keras.layers.Dense(units=128)
layer7 = tf.keras.layers.Dense(units=128)
layer8 = tf.keras.layers.Dense(units=64)
layer9 = tf.keras.layers.Dense(units=1)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [14]:
#step 2: add all layers tomodel
model = tf.keras.Sequential()
model.add(layer1)
model.add(layer2)
model.add(layer3)
model.add(layer4)
model.add(layer5)
model.add(layer6)
model.add(layer7)
model.add(layer8)
model.add(layer9)
model.add(layer10)

In [15]:
#step 3: giveoptimizer and loss function to model
model.compile(optimizer='adam',loss='mean_squared_error',metrics = ['mean_squared_error'])

In [16]:
model.fit(x,y,epochs=500)

Epoch 1/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 12.0070 - mean_squared_error: 12.0070
Epoch 2/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.6623 - mean_squared_error: 10.6623
Epoch 3/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 9.3614 - mean_squared_error: 9.3614
Epoch 4/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 10.4157 - mean_squared_error: 10.4157
Epoch 5/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 9.2375 - mean_squared_error: 9.2375
Epoch 6/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 8.9126 - mean_squared_error: 8.9126
Epoch 7/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.7577 - mean_squared_error: 9.7577
Epoch 8/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.9357 - mean_squared_error: 7.9357
Epoch 9/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7.8137 - mean_squared_error: 7.8137
Epoch 10/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.2821 - mean_squared_error: 8.2821
Epoch 11/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.0145 - mean_squared_error: 7.0145
Epoch 12/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.8570 - mean_squared_error: 6.8570
Epoch 13/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.1887 - mean_squared_error: 7.1887
Epoch 14/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.6567 - mean_squared_error: 6.6567
Epoch 15/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.0295 - mean_squared_error: 6.0295
Epoch 16/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6.2305 - mean_squared_error: 6.2305
Epoch 17/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.4605 - mean_squared_error: 5.4605
Epoch 18/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 5.3762 - mean_squared_error: 5.3762
Epoch 19/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.0929 - mean_squared_error: 5.0929
Epoch 20/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.3244 - mean_squared_error: 5.3244
Epoch 21/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 4.6772 - mean_squared_error: 4.6772
Epoch 22/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.1123 - mean_squared_error: 4.1123
Epoch 23/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.3503 - mean_squared_error: 4.3503
Epoch 24/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.7618 - mean_squared_error: 3.7618
Epoch 25/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 3.6676 - mean_squared_error: 3.6676
Epoch 26/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 3.5575 - mean_squared_error: 3.5575
Epoch 27/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.3862 - mean_squared_error: 3.3862
Epoch 28/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 3.2354 - mean_squared_error: 3.2354
Epoch 29/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.9803 - mean_squared_error: 2.9803
Epoch 30/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2.7780 - mean_squared_error: 2.7780
Epoch 31/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 2.7042 - mean_squared_error: 2.7042
Epoch 32/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.8425 - mean_squared_error: 2.8425
Epoch 33/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.4606 - mean_squared_error: 2.4606
Epoch 34/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 2.3583 - mean_squared_error: 2.3583
Epoch 35/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 2.1550 - mean_squared_error: 2.1550
Epoch 36/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.0516 - mean_squared_error: 2.0516
Epoch 37/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 1.7789 - mean_squared_error: 1.7789
Epoch 38/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.6917 - mean_squared_error: 1.6917
Epoch 39/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.6030 - mean_squared_error: 1.6030
Epoch 40/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.6962 - mean_squared_error: 1.6962
Epoch 41/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.9324 - mean_squared_error: 1.9324
Epoch 42/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.4788 - mean_squared_error: 1.4788
Epoch 43/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 1.2907 - mean_squared_error: 1.2907
Epoch 44/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1.4869 - mean_squared_error: 1.4869
Epoch 45/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.5094 - mean_squared_error: 1.5094
Epoch 46/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.3820 - mean_squared_error: 1.3820
Epoch 47/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 1.1603 - mean_squared_error: 1.1603
Epoch 48/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.1770 - mean_squared_error: 1.1770
Epoch 49/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 1.1266 - mean_squared_error: 1.1266
Epoch 50/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.1633 - mean_squared_error: 1.1633
Epoch 51/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1349 - mean_squared_error: 1.1349
Epoch 52/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.1603 - mean_squared_error: 1.1603
Epoch 53/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9983 - mean_squared_error: 0.9983
Epoch 54/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.1474 - mean_squared_error: 1.1474
Epoch 55/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0380 - mean_squared_error: 1.0380
Epoch 56/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.1229 - mean_squared_error: 1.1229
Epoch 57/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9996 - mean_squared_error: 0.9996
Epoch 58/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0287 - mean_squared_error: 1.0287
Epoch 59/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.8712 - mean_squared_error: 0.8712
Epoch 60/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 1.1290 - mean_squared_error: 1.1290
Epoch 61/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 1.0944 - mean_squared_error: 1.0944
Epoch 62/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8914 - mean_squared_error: 0.8914
Epoch 63/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1820 - mean_squared_error: 1.1820
Epoch 64/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1583 - mean_squared_error: 1.1583
Epoch 65/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9723 - mean_squared_error: 0.9723
Epoch 66/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.3000 - mean_squared_error: 1.3000
Epoch 67/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1812 - mean_squared_error: 1.1812
Epoch 68/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.2661 - mean_squared_error: 1.2661
Epoch 69/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0230 - mean_squared_error: 1.0230
Epoch 70/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1374 - mean_squared_error: 1.1374
Epoch 71/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9835 - mean_squared_error: 0.9835
Epoch 72/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1976 - mean_squared_error: 1.1976
Epoch 73/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0385 - mean_squared_error: 1.0385
Epoch 74/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0574 - mean_squared_error: 1.0574
Epoch 75/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0086 - mean_squared_error: 1.0086
Epoch 76/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.1718 - mean_squared_error: 1.1718
Epoch 77/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0115 - mean_squared_error: 1.0115
Epoch 78/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0708 - mean_squared_error: 1.0708
Epoch 79/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0556 - mean_squared_error: 1.0556
Epoch 80/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0839 - mean_squared_error: 1.0839
Epoch 81/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0189 - mean_squared_error: 1.0189
Epoch 82/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1274 - mean_squared_error: 1.1274
Epoch 83/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0985 - mean_squared_error: 1.0985
Epoch 84/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9922 - mean_squared_error: 0.9922
Epoch 85/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1289 - mean_squared_error: 1.1289
Epoch 86/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1644 - mean_squared_error: 1.1644
Epoch 87/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0560 - mean_squared_error: 1.0560
Epoch 88/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0926 - mean_squared_error: 1.0926
Epoch 89/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.4086 - mean_squared_error: 1.4086
Epoch 90/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1360 - mean_squared_error: 1.1360
Epoch 91/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0503 - mean_squared_error: 1.0503
Epoch 92/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0520 - mean_squared_error: 1.0520
Epoch 93/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0841 - mean_squared_error: 1.0841
Epoch 94/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0008 - mean_squared_error: 1.0008
Epoch 95/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9716 - mean_squared_error: 0.9716
Epoch 96/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0461 - mean_squared_error: 1.0461
Epoch 97/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.9859 - mean_squared_error: 0.9859
Epoch 98/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.0475 - mean_squared_error: 1.0475
Epoch 99/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.1392 - mean_squared_error: 1.1392
Epoch 100/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0625 - mean_squared_error: 1.0625
Epoch 101/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1719 - mean_squared_error: 1.1719
Epoch 102/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0928 - mean_squared_error: 1.0928
Epoch 103/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0584 - mean_squared_error: 1.0584
Epoch 104/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1182 - mean_squared_error: 1.1182
Epoch 105/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1053 - mean_squared_error: 1.1053
Epoch 106/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0255 - mean_squared_error: 1.0255
Epoch 107/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1231 - mean_squared_error: 1.1231
Epoch 108/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9784 - mean_squared_error: 0.9784
Epoch 109/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0658 - mean_squared_error: 1.0658
Epoch 110/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1790 - mean_squared_error: 1.1790
Epoch 111/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9310 - mean_squared_error: 0.9310
Epoch 112/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1747 - mean_squared_error: 1.1747
Epoch 113/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0038 - mean_squared_error: 1.0038
Epoch 114/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1182 - mean_squared_error: 1.1182
Epoch 115/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.2584 - mean_squared_error: 1.2584
Epoch 116/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1912 - mean_squared_error: 1.1912
Epoch 117/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.2771 - mean_squared_error: 1.2771
Epoch 118/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.2131 - mean_squared_error: 1.2131
Epoch 119/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1130 - mean_squared_error: 1.1130
Epoch 120/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9744 - mean_squared_error: 0.9744
Epoch 121/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0508 - mean_squared_error: 1.0508
Epoch 122/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9251 - mean_squared_error: 0.9251
Epoch 123/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.2840 - mean_squared_error: 1.2840
Epoch 124/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0926 - mean_squared_error: 1.0926
Epoch 125/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0448 - mean_squared_error: 1.0448
Epoch 126/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0583 - mean_squared_error: 1.0583
Epoch 127/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9968 - mean_squared_error: 0.9968
Epoch 128/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9767 - mean_squared_error: 0.9767
Epoch 129/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0206 - mean_squared_error: 1.0206
Epoch 130/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.0542 - mean_squared_error: 1.0542
Epoch 131/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1061 - mean_squared_error: 1.1061
Epoch 132/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0251 - mean_squared_error: 1.0251
Epoch 133/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0569 - mean_squared_error: 1.0569
Epoch 134/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0204 - mean_squared_error: 1.0204
Epoch 135/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1431 - mean_squared_error: 1.1431
Epoch 136/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0108 - mean_squared_error: 1.0108
Epoch 137/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8542 - mean_squared_error: 0.8542
Epoch 138/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9681 - mean_squared_error: 0.9681
Epoch 139/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1968 - mean_squared_error: 1.1968
Epoch 140/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1610 - mean_squared_error: 1.1610
Epoch 141/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0210 - mean_squared_error: 1.0210
Epoch 142/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1076 - mean_squared_error: 1.1076
Epoch 143/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0563 - mean_squared_error: 1.0563
Epoch 144/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1118 - mean_squared_error: 1.1118
Epoch 145/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.1494 - mean_squared_error: 1.1494
Epoch 146/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.1640 - mean_squared_error: 1.1640
Epoch 147/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1265 - mean_squared_error: 1.1265
Epoch 148/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1133 - mean_squared_error: 1.1133
Epoch 149/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1001 - mean_squared_error: 1.1001
Epoch 150/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9291 - mean_squared_error: 0.9291
Epoch 151/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9381 - mean_squared_error: 0.9381
Epoch 152/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0689 - mean_squared_error: 1.0689
Epoch 153/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9315 - mean_squared_error: 0.9315
Epoch 154/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1667 - mean_squared_error: 1.1667
Epoch 155/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.0923 - mean_squared_error: 1.0923
Epoch 156/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1781 - mean_squared_error: 1.1781
Epoch 157/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0298 - mean_squared_error: 1.0298
Epoch 158/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1280 - mean_squared_error: 1.1280
Epoch 159/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1249 - mean_squared_error: 1.1249
Epoch 160/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.2199 - mean_squared_error: 1.2199
Epoch 161/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0204 - mean_squared_error: 1.0204
Epoch 162/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9131 - mean_squared_error: 0.9131
Epoch 163/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3133 - mean_squared_error: 1.3133
Epoch 164/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.3434 - mean_squared_error: 1.3434
Epoch 165/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0308 - mean_squared_error: 1.0308
Epoch 166/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0666 - mean_squared_error: 1.0666
Epoch 167/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1770 - mean_squared_error: 1.1770
Epoch 168/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9409 - mean_squared_error: 0.9409
Epoch 169/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.9564 - mean_squared_error: 0.9564
Epoch 170/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9884 - mean_squared_error: 0.9884
Epoch 171/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9747 - mean_squared_error: 0.9747
Epoch 172/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9954 - mean_squared_error: 0.9954
Epoch 173/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0275 - mean_squared_error: 1.0275
Epoch 174/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9859 - mean_squared_error: 0.9859
Epoch 175/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9943 - mean_squared_error: 0.9943
Epoch 176/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0525 - mean_squared_error: 1.0525
Epoch 177/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0716 - mean_squared_error: 1.0716
Epoch 178/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9906 - mean_squared_error: 0.9906
Epoch 179/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1205 - mean_squared_error: 1.1205
Epoch 180/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0495 - mean_squared_error: 1.0495
Epoch 181/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8969 - mean_squared_error: 0.8969
Epoch 182/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0145 - mean_squared_error: 1.0145
Epoch 183/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1403 - mean_squared_error: 1.1403
Epoch 184/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9890 - mean_squared_error: 0.9890
Epoch 185/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.2575 - mean_squared_error: 1.2575
Epoch 186/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1141 - mean_squared_error: 1.1141
Epoch 187/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9924 - mean_squared_error: 0.9924
Epoch 188/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0892 - mean_squared_error: 1.0892
Epoch 189/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9624 - mean_squared_error: 0.9624
Epoch 190/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0223 - mean_squared_error: 1.0223
Epoch 191/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.1865 - mean_squared_error: 1.1865
Epoch 192/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.2401 - mean_squared_error: 1.2401
Epoch 193/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0474 - mean_squared_error: 1.0474
Epoch 194/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0045 - mean_squared_error: 1.0045
Epoch 195/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.1185 - mean_squared_error: 1.1185
Epoch 196/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.0998 - mean_squared_error: 1.0998
Epoch 197/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0085 - mean_squared_error: 1.0085
Epoch 198/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.9947 - mean_squared_error: 0.9947
Epoch 199/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.8431 - mean_squared_error: 0.8431
Epoch 200/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.2000 - mean_squared_error: 1.2000
Epoch 201/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.0491 - mean_squared_error: 1.0491
Epoch 202/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.9874 - mean_squared_error: 0.9874
Epoch 203/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0628 - mean_squared_error: 1.0628
Epoch 204/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1221 - mean_squared_error: 1.1221
Epoch 205/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1574 - mean_squared_error: 1.1574
Epoch 206/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9906 - mean_squared_error: 0.9906
Epoch 207/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.8616 - mean_squared_error: 0.8616
Epoch 208/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0684 - mean_squared_error: 1.0684
Epoch 209/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 0.9693 - mean_squared_error: 0.9693
Epoch 210/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0044 - mean_squared_error: 1.0044
Epoch 211/500
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.0767 - mean_squared_error: 1.0767
Epoch 212/500

In [17]:
df.head()

   total_bill   tip sex smoker day time  size
0       16.99  1.01   0      0   1    0     2
1       10.34  1.66   1      0   1    0     3
2       21.01  3.50   1      0   1    0     3
3       23.68  3.31   1      0   1    0     2
4       24.59  3.61   0      0   1    0     4

In [18]:
model.predict(np.array([[21.01,1,0,1,0,3]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step

array([[3.2859912, 3.286002 , 3.28604  , 3.2860243, 3.285517 , 3.2857292,
        3.28604  , 3.2857506, 3.2860415, 3.2859735, 3.286024 , 3.2860413,
        3.285881 , 3.2858558, 3.2860413, 3.2860398, 3.2860305, 3.2859802,
        3.2856677, 3.2852864, 3.2859585, 3.28539  , 3.2860396, 3.285798 ,
        3.2854953, 3.2854779, 3.2859912, 3.2854376, 3.285541 , 3.285328 ,
        3.2859972, 3.2857785, 3.2858005, 3.2855918, 3.2858021, 3.2856102,
        3.2860358, 3.28602  , 3.2860265, 3.2858253, 3.285994 , 3.2860408,
        3.2859664, 3.2860255, 3.2859507, 3.286025 , 3.2860417, 3.2855897,
        3.2860415, 3.2859933, 3.2859862, 3.2859683, 3.285966 , 3.2859426,
        3.285706 , 3.2860355, 3.2855387, 3.2860074, 3.2859886, 3.286025 ,
        3.2857184, 3.2858274, 3.2859576, 3.286002 ]], dtype=float32)

In [19]:
#more the layers will get most accurate answer
model.predict(np.array([[16.99,1.01,0,1,0,2]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step

array([[2.751514 , 2.7510717, 2.7483723, 2.7498744, 2.7657785, 2.759713 ,
        2.7481918, 2.7591217, 2.7472336, 2.7522545, 2.7498915, 2.7470887,
        2.7553077, 2.7560723, 2.7465172, 2.7482417, 2.7494066, 2.7519908,
        2.7614446, 2.7733037, 2.7528038, 2.7697232, 2.7482688, 2.7577498,
        2.766439 , 2.766959 , 2.7515247, 2.7681856, 2.7650757, 2.7718263,
        2.7512915, 2.7583075, 2.7576873, 2.7636003, 2.7576513, 2.7630758,
        2.7489173, 2.7501328, 2.7497432, 2.7569673, 2.7514048, 2.7464325,
        2.7525082, 2.7497957, 2.753081 , 2.7498403, 2.7474978, 2.7636724,
        2.7478805, 2.7514505, 2.7517445, 2.7524383, 2.7524915, 2.753354 ,
        2.7603695, 2.748891 , 2.7651582, 2.7508144, 2.7516532, 2.7498796,
        2.7600124, 2.7569225, 2.7528257, 2.7510498]], dtype=float32)